# Generated by Django 5.1.14 on 2026-01-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0070_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='auth_type',
            field=models.CharField(choices=[('oauth', 'OAuth'), ('service_account', 'Service Account')], default='oauth', max_length=20),
        ),
    ]
