# Generated by Django 5.1.14 on 2026-01-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0071_add_calendar_auth_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleWatchChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('channel_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('resource_id', models.CharField(max_length=255)),
                ('expiration', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_channels', to='bots.calendar')),
            ],
            options={
                'verbose_name': 'Google Watch Channel',
                'verbose_name_plural': 'Google Watch Channels',
            },
        ),
        migrations.CreateModel(
            name='OAuthCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=20)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField()),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_credentials', to='bots.calendar')),
            ],
            options={
                'verbose_name': 'OAuth Credential',
                'verbose_name_plural': 'OAuth Credentials',
                'unique_together': {('email', 'provider')},
            },
        ),
    ]
