# Generated by Django 5.1.14 on 2026-01-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_wide', '0001_initial_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('supabase_sync', 'Supabase Sync'), ('meeting_insights', 'Meeting Insights'), ('email_sent', 'Email Sent')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=16)),
                ('bot_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('meeting_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('meeting_title', models.CharField(blank=True, max_length=255)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Pipeline Activity',
                'verbose_name_plural': 'Pipeline Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
